# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Topics
    url: tags/
    weight: 20
  - name: Projects
    url: projects/
    weight: 30
    children:
      - name: Python
        url: projects/Python/
        weight: 10
      - name: Project 2
        url: projects/project2/
        weight: 20
